// Phase 2 — Data-Driven Glyph Ramp
//
// This file is GENERATED by `cargo run --bin generate_ramp`.
// Do not edit by hand — run the generator and copy its stdout here.
// To regenerate: `cargo run --bin generate_ramp -- --ramp-size 16 --font-size 32`

/// 16-character perceptually-uniform ramp generated from DejaVu Sans Mono
/// at 32px raster size using fontdue ink-density measurement.
/// Density range: [0.0000, 0.8683]
pub const RAMP: &[char] = &[' ', '/', '\\', 'i', 'l', '`', 'Z', 'z', 'n', '"', '-', '!', '.', '\'', '|', '_'];

#[cfg(test)]
mod tests {
    use super::*;
    use crate::render::ascii::{AsciiRenderer, ColorMode};

    #[test]
    fn test_generated_ramp_bounds() {
        let renderer = AsciiRenderer::new(&RAMP.iter().collect::<String>(), ColorMode::Monochrome, false);
        assert_eq!(renderer.luminance_to_char(0), ' ');
        assert_eq!(renderer.luminance_to_char(255), '_');
    }

    #[test]
    fn test_generated_ramp_monotonic() {
        // RAMP should be strictly increasing in visual density
        let renderer = AsciiRenderer::new(&RAMP.iter().collect::<String>(), ColorMode::Monochrome, false);
        let mut last = ' ';
        for lum in 0..=255 {
            let ch = renderer.luminance_to_char(lum);
            if ch != last {
                // Ensure we can find ch later in RAMP (rough check)
                assert!(RAMP.iter().position(|&c| c == ch).is_some());
                last = ch;
            }
        }
    }
}