[target.x86_64-pc-windows-gnu]
linker = "C:\\msys64\\mingw64\\bin\\gcc.exe"
ar = "C:\\msys64\\mingw64\\bin\\ar.exe"

[env]
PATH = { value = "C:\\msys64\\mingw64\\bin;C:\\Windows\\system32;C:\\Windows", relative = false }
